version: '3.8'

services:
  app:
    build: .
    container_name: caduceus
    ports:
      - "8000:8000"
      - "8501:8501"
      - "8502:8502"
    networks:
      - network
    volumes:
      - ./Cache:/app/Cache

networks:
  network:
    driver: bridge